# Generated by Django 5.0.7 on 2024-09-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_author_book_author_m_alter_book_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_m',
            new_name='author',
        ),
    ]
