# Generated by Django 5.0.7 on 2024-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_author_m_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='exist',
            field=models.BooleanField(default=False),
        ),
    ]
