# Generated by Django 5.0.7 on 2024-09-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_gap', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
