# Generated by Django 5.0.7 on 2024-08-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author_khadamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic_author',
            field=models.ImageField(null=True, upload_to='upload_author/'),
        ),
    ]
