# Generated by Django 5.0.7 on 2024-08-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_model_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_comment',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
