# Generated by Django 5.0.7 on 2024-08-29 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_model_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='blog.post'),
        ),
    ]
