# Generated by Django 5.0.7 on 2024-09-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_model_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_comment',
            name='name',
        ),
    ]
